[package]
name = "suricata-derive"
version = "7.0.0"
edition = "2021"

[lib]
proc-macro = true
path = "/home/zhengkt/ids/engine/rust/derive/src/lib.rs"

[dependencies]
proc-macro-crate = "= 1.1.0"
proc-macro2 = "1.0.36"
quote = "1.0"
syn = "1.0"
